### ISSUE TITLE
Site is not mobile responsive

### ISSUE THREAD

**Issue by dakxh** [21R01A7263/Youtube_Video_Categorizer#1]
Currently, the site is not well optimized for mobile view ports. 

![image](https://github.com/21R01A7263/Youtube_Video_Categorizer/assets/89646853/286ea8ff-211f-4558-8982-dfeded2ab5b9)

**Comment by Vaishali785** [comment]
Hi @Dakxh ,  I would like to work on this. Can you assign this issue to me?

**Comment by bhalerao-2002** [comment]
Ok @Dakxh, I have worked on issues like that many times, As your website is small, It will not take much time to fix it.
We can discuss about the design you want in Mobile view, so it will be more satisfactory.
Assign me this under hactoberfest :) Happy Developing 👌
Your work is fantastic as a Beginner. Appreciated

**Comment by gaurav-saiteja** [comment]
> Hi @Dakxh , I would like to work on this. Can you assign this issue to me?

Hello, there. I am the maintainer of this repository and I am assigning this issue to you under "Hacktoberfest". Good Luck!

**Comment by gaurav-saiteja** [comment]
> Ok @Dakxh, I have worked on issues like that many times, As your website is small, It will not take much time to fix it. We can discuss about the design you want in Mobile view, so it will be more satisfactory. Assign me this under hactoberfest :) Happy Developing 👌 Your work is fantastic as a Beginner. Appreciated

I have assigned this issue to you under the event "Hacktoberfest". Hoping to merge your Pull Request soon!.

**Comment by Vaishali785** [comment]
Hi @21R01A7263 , thanks for assigning this to me. But just want to confirm one thing, can two people together work on this issue under hacktoberfest?

> > Hi @Dakxh , I would like to work on this. Can you assign this issue to me?
> 
> Hello, there. I am the maintainer of this repository and I am assigning this issue to you under "Hacktoberfest". Good Luck!

Hi @21R01A7263 , thanks for assigning this to me. But just want to confirm one thing, can two people together work on this issue under hacktoberfest?

**Comment by gaurav-saiteja** [comment]
> Hi @21R01A7263 , thanks for assigning this to me. But just want to confirm one thing, can two people together work on this issue under hacktoberfest?
> 
> > > Hi @Dakxh , I would like to work on this. Can you assign this issue to me?
> > 
> > 
> > Hello, there. I am the maintainer of this repository and I am assigning this issue to you under "Hacktoberfest". Good Luck!
> 
> Hi @21R01A7263 , thanks for assigning this to me. But just want to confirm one thing, can two people together work on this issue under hacktoberfest?

Yes @Vaishali785. Multiple people can be assigned to the same issue. The Pull request with the least conflicts with main branch will be merged.
